### ISSUE TITLE
Don-t remove empty lines in top level expressions in fsx files

### ISSUE THREAD

**Issue by ovatsus** [dungpa/fantomas#134] opened 2014-02-06 11:28 UTC
Example:

```
this
|> is
|> snippet1

this
|> is
|> snippet2
```

is turned into

```
this
|> is
|> snippet1
this
|> is
|> snippet2
```

**Comment by dsyme** [comment] 2017-09-10 16:11
Closing as duplicate of https://github.com/dungpa/fantomas/issues/143

**Closed by dsyme** 2017-09-10 16:11 UTC
Labels: bug (stylistic)
