### ISSUE TITLE
Input file is wiped if inputFile = outputFile and exception happens

### ISSUE THREAD

**Issue by ohwang** [dungpa/fantomas#180] opened 2015-10-10 14:11 UTC
Edit: This is a bug when using Fantomas in command line.

Exception is handled inside ``fileToFile`` but when exception happens, the remaining operation still goes on resulting an empty ``inputFile``

```fsharp
    let processFile inputFile outputFile config =
        if inputFile <> outputFile then
            fileToFile inputFile outputFile config
        else
            let tempFile = Path.GetTempFileName()
            fileToFile inputFile tempFile config
            File.Delete(inputFile)
            File.Move(tempFile,inputFile)
```

This happened to me because of an incorrect Fantomas setup, thankfully I do not have uncommitted changes, but the result can be unrecoverable in unfortunate cases.

**Comment by dungpa** [comment] 2015-11-11 21:21
Thanks for reporting this. The issue is fixed now.

**Closed** 2015-11-11 21:21 UTC
